# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2019_11_08_142154) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "establishments", force: :cascade do |t|
    t.string "title"
    t.string "statut"
    t.string "breakfast"
    t.string "property_type"
    t.string "full_board"
    t.string "internet"
    t.string "parking"
    t.string "pet"
    t.string "household_linen"
    t.string "cleaning_package"
    t.string "address"
    t.string "home_type"
    t.string "room_type"
    t.string "address_detail"
    t.string "phone_number"
    t.string "establishment_name"
    t.string "pmr_room_type"
    t.string "email_resa"
    t.string "situation"
    t.string "channel_manager"
    t.string "internal_contact"
    t.string "nurse_name"
    t.string "nurse_phone"
    t.string "nurse_email"
    t.string "nurse_address"
    t.string "medical_equipement_name"
    t.string "medical_equipement_phone"
    t.string "medical_equipement_email"
    t.string "medical_equipement_address"
    t.string "medical_equipement_support_name"
    t.string "medical_equipement_support_phone"
    t.string "medical_equipement_support_email"
    t.string "medical_equipement_support_address"
    t.string "listing_name"
    t.boolean "swimming_pool"
    t.boolean "suitable_swimming_pool"
    t.boolean "television"
    t.string "washing_machine"
    t.boolean "air_conditionning"
    t.boolean "kitchen"
    t.boolean "elevator"
    t.boolean "intercom"
    t.boolean "medical_bed"
    t.boolean "person_lift"
    t.boolean "hearing_handicap"
    t.boolean "physical_handicap"
    t.boolean "mental_handicap"
    t.boolean "visual_handicap"
    t.boolean "is_certified"
    t.boolean "suitable_shower"
    t.boolean "one_level"
    t.boolean "allow_immediate_booking"
    t.boolean "for_families"
    t.boolean "smokers_accepted"
    t.boolean "suited_for_event"
    t.boolean "beach"
    t.boolean "shop"
    t.boolean "city_center"
    t.boolean "public_transport"
    t.boolean "restaurant"
    t.boolean "night_life"
    t.boolean "flexible"
    t.boolean "is_tv"
    t.boolean "is_kitchen"
    t.boolean "is_air"
    t.boolean "is_heating"
    t.boolean "is_internet"
    t.boolean "active"
    t.boolean "smoker_accepted"
    t.boolean "is_breakfast"
    t.boolean "is_half_board"
    t.boolean "is_full_board"
    t.boolean "is_parking"
    t.boolean "is_cleaning_pack"
    t.boolean "is_pet"
    t.boolean "known_owner"
    t.boolean "is_channel_manager"
    t.float "breakfast_price"
    t.float "half_board_price"
    t.float "full_board_price"
    t.float "internet_price"
    t.float "parking_price"
    t.float "pet_price"
    t.float "household_linen_price"
    t.float "cleaning_package_price"
    t.float "arrival_min_time"
    t.float "arrival_max_time"
    t.float "leaving_min_time"
    t.float "leaving_max_time"
    t.float "price"
    t.float "deposit_amount"
    t.float "tax_amount"
    t.float "edited_commission"
    t.float "commission"
    t.float "fixed_commission"
    t.float "size"
    t.float "sink_height"
    t.float "door_width"
    t.float "latitude"
    t.float "longitude"
    t.text "external_calendar_url"
    t.text "description"
    t.text "details_resa"
    t.text "info_commission"
    t.text "summary"
    t.integer "capacity"
    t.integer "room"
    t.integer "bath_rooms"
    t.integer "bed"
    t.integer "accommodate"
    t.integer "bed_room"
    t.integer "bath_room"
    t.integer "instant", default: 1
    t.integer "mobee_classification"
    t.integer "stars_classification"
    t.bigint "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "photos", default: [], array: true
    t.string "half_board"
    t.string "city"
    t.string "first_image"
    t.string "country"
    t.string "country_code"
    t.string "postal_code"
    t.string "zipcode"
    t.boolean "medical_equipement"
    t.index ["user_id"], name: "index_establishments_on_user_id"
  end

  create_table "reservations", force: :cascade do |t|
    t.bigint "user_id"
    t.bigint "establishment_id"
    t.datetime "start_date"
    t.datetime "end_date"
    t.integer "price"
    t.integer "total"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["establishment_id"], name: "index_reservations_on_establishment_id"
    t.index ["user_id"], name: "index_reservations_on_user_id"
  end

  create_table "reviews", force: :cascade do |t|
    t.text "comment"
    t.integer "star", default: 1
    t.bigint "establishment_id"
    t.bigint "reservation_id"
    t.bigint "guest_id"
    t.bigint "host_id"
    t.string "type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["establishment_id"], name: "index_reviews_on_establishment_id"
    t.index ["guest_id"], name: "index_reviews_on_guest_id"
    t.index ["host_id"], name: "index_reviews_on_host_id"
    t.index ["reservation_id"], name: "index_reviews_on_reservation_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "first_name"
    t.string "last_name"
    t.string "facebook_id"
    t.string "google_id"
    t.string "phone_number"
    t.string "pin"
    t.string "address"
    t.string "company_name"
    t.string "compagny_business"
    t.string "company_website"
    t.string "company_tax_id"
    t.string "iban"
    t.string "bic"
    t.string "role"
    t.string "avatar"
    t.string "others_accessibility_need"
    t.string "others_medical_help_need"
    t.string "gender"
    t.string "stripe_id"
    t.string "merchant_id"
    t.string "merchant_provider"
    t.string "merchant_access_code"
    t.string "merchant_publishable_key"
    t.string "class_name"
    t.string "agency_network"
    t.string "name"
    t.string "fullname"
    t.string "provider"
    t.string "uid"
    t.text "description"
    t.boolean "phone_verified"
    t.boolean "medical_bed"
    t.boolean "person_lift"
    t.boolean "nurse"
    t.boolean "help_to_the_person"
    t.boolean "physio_therapist"
    t.boolean "admin", default: false
    t.boolean "pro", default: false, null: false
    t.date "birth_date"
    t.integer "unread", default: 1
    t.float "cell"
    t.string "image"
    t.string "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "establishments", "users"
  add_foreign_key "reservations", "establishments"
  add_foreign_key "reservations", "users"
  add_foreign_key "reviews", "establishments"
  add_foreign_key "reviews", "reservations"
  add_foreign_key "reviews", "users", column: "guest_id"
  add_foreign_key "reviews", "users", column: "host_id"
end
